[project]
name = "expense-tracker"
version = "0.1.0"
description = "Personal expense tracking application with FastAPI backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # Core FastAPI and web server
    "fastapi>=0.116.0",
    "uvicorn[standard]>=0.35.0",
    
    # Database and ORM
    "sqlalchemy>=2.0.41",
    
    # Authentication and security
    "python-jose[cryptography]>=3.5.0",
    "bcrypt>=4.3.0",  # Use bcrypt directly instead of passlib
    
    # Data validation and parsing
    "pydantic[email]>=2.11.7",
    "python-multipart>=0.0.20",
    "email-validator>=2.2.0",
    
    # Testing
    "pytest>=8.4.1",
    "httpx>=0.27.2",
]

[project.optional-dependencies]
dev = [
    # Development tools
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.5.0",
]

# Simplified build system - no editable install needed for this project structure
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["backend/tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--tb=short",
    "--strict-markers",
]
# Filter out external library warnings we can't control
filterwarnings = [
    "ignore::DeprecationWarning:passlib.*",
]

[tool.black]
line-length = 100
target-version = ["py312"]
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true